### PR TITLE
Add mu_roadmap repo support [Rebase & FF]

### PR DESCRIPTION
**Pull request by makubacki**
Updates file sync and the notebooks to be aware of mu_roadmap.

https://github.com/microsoft/mu_roadmap/

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>

### CODE REVIEW

**Comment by spbrogan** [comment]
should we do a custom issues template.  Cut out most of the common stuff and put in only a template for "tracking item"

**Comment by makubacki** [comment]
> should we do a custom issues template. Cut out most of the common stuff and put in only a template for "tracking item"

Yeah, that would help funnel people down the right path in that repo. I'll add it here.

**Review by apop5 — APPROVED** [review]

**Comment by makubacki** [comment]
Made some small changes based on offline discussion. Mainly that the `type:tracking-issue` label and `tracking_item.yml` pieces are currently only relevant for mu_roadmap. So, I removed them from here to keep them in that repo.

**Comment by apop5** [comment]
Not stale.

**Comment by makubacki** [comment]
I'll close this PR for now and reopen when the mu_roadmap repo is available.

**Pull request closed without merging**
